### ISSUE TITLE
Filters not getting set when including them in embedconfiguration

### ISSUE THREAD

**Issue by brannmar** [Microsoft/PowerBI-JavaScript#248]
Hi!

We are experiencing an issue where filter included in the embedconfiguration are not getting set properly. This began in the recent days, not sure really but before the summer there was no problems that i know of. 

Se our embedconfiguration here
```javascript
var embedConfiguration = {
    type: 'report',
    accessToken: reportdata.AccessToken,
    id: reportdata.Report.Id,
    embedUrl: (reportdata.EmbedUrl + "&filterPaneEnabled=false&navContentPaneEnabled=false&width=1000"),
    settings: {
        filterPaneEnabled: false,
        navContentPaneEnabled: false
    },
    filters: [{
        $schema: "http://powerbi.com/product/schema#advanced",
        target: {
            table: "Customer",
            column: "CustomerId"
        },
        logicalOperator: "Or",
        conditions: conditions
    }]
};
```

when the report is loaded the filters are not correctly applied. 

![image](https://user-images.githubusercontent.com/7968452/30053938-b766961e-922a-11e7-80b5-d4dc74dbd2fe.png)

The way we have to solve this now is to apply the filters when the report i loaded. 

Is this the expected behaviour?

**Comment by brannmar** [comment]
We are using version v2.2.6.

**Comment by prasy14** [comment]
I am having the same issue , it was working previously and since yesterday it broke

  var MyFilter = {
                $schema: "http://powerbi.com/product/schema#basic",
                target: {
                    table: "Provider",
                    column: "Name"
                },
                operator: "In",
                values: "xyz"
}

 var config = {
                type: 'report',
                accessToken: accessToken,
                embedUrl: embedUrl,
                pagename:"ReportSection",
                id: reportId,
               filters: [MyFilter],
                settings: {
                    filterPaneEnabled: true,
                    navContentPaneEnabled: false
                }
                
            };

 // Embed the report and display it within the div container.
            var report = powerbi.embed(reportContainer, config);

**Comment by zhll2046** [comment]
I can reproduce the same issue. Both setting filter in config or report.setFilter don't work.

**Comment by ali-hamud** [comment]
Hi,
issue found and fixed. ETA for the fix: next week.

**Comment by ali-hamud** [comment]
Issue is fixed and deployed. please validate.

**Comment by djnhh0an** [comment]
@ali-hamud:  Could you tell me which version you deployed it? I still get the same issue with version 2.3.5

**Comment by djnhh0an** [comment]
Dear Mr @ali-hamud !
I'm writing the code in ReactJs and use TypeScript:
`public componentDidMount() {
        let reportContainer = document.getElementById(this.props.elementId);
        let embedConfiguration: IEmbedConfiguration = {
            type: 'report',
            id: this.props.embedReport.report.id,
            embedUrl: this.props.embedReport.report.embedUrl,
            accessToken: this.props.embedReport.accessToken,
            pageName: this.props.pageName,
            filters: this.props.filters,
            settings : this.props.settings
        }
        let service = new powerbi.service.Service(powerbi.factories.hpmFactory, powerbi.factories.wpmpFactory, powerbi.factories.routerFactory);
        service.embed(reportContainer, embedConfiguration);
    }`
Thank for replying!
Regards,
Hoan Tran

**Comment by djnhh0an** [comment]
Dear Mr @ali-hamud !
This is embededURL: https://embedded.powerbi.com/appTokenReportEmbed?reportId=08b6d3a8-097c-4c9a-b484-fb7eb4fffc1f
I'm writing the code in ReactJs and use TypeScript, this is a method I embbed the report:
`public componentDidMount() { 
let reportContainer = document.getElementById(this.props.elementId); let embedConfiguration: IEmbedConfiguration = { type: 'report', id: this.props.embedReport.report.id, embedUrl: this.props.embedReport.report.embedUrl, accessToken: this.props.embedReport.accessToken, pageName: this.props.pageName, filters: this.props.filters, settings : this.props.settings } let service = new powerbi.service.Service(powerbi.factories.hpmFactory, powerbi.factories.wpmpFactory, powerbi.factories.routerFactory); service.embed(reportContainer, embedConfiguration); }`
Thank for replying!
Regards,
Hoan Tran

**Comment by ali-hamud** [comment]
I see.
I succeeded to reproduce the issue with
appTokenRepotEmbed. I will update on ETA later.

**Comment by djnhh0an** [comment]
@ali-hamud: Thank you so much! This is the biggest problem with our system at the moment, it's very important for us, could you please tell me about your plan for this issue? 
Regards,
Hoan Tran

**Comment by ali-hamud** [comment]
The fix is in deployment process, we will deploy it asap, let me update on Monday.
Thanks.

**Comment by djnhh0an** [comment]
@ali-hamud: That's great! Thank you so much!

**Comment by djnhh0an** [comment]
Dear Mr @ali-hamud,
Do you have any update for today?
Thanks,
Hoan Tran

**Comment by ali-hamud** [comment]
sure.
If everything goes as planned, fix expected to get deployed this upcoming Friday.

**Comment by djnhh0an** [comment]
Thank you, Mr @ali-hamud! We're waiting for your team day by day :)

**Comment by ali-hamud** [comment]
Fix deployed to Production env on last Friday.
please check.

**Comment by djnhh0an** [comment]
@ali-hamud: Thank you so much!
Hoan Tran
